$ ->
#  $('.sportaide_search').search(
#    type: 'category'
#    apiSettings:
#      url: '/courses/search_courses_main?term={query}'
#    fields:
#      results: 'results',
#      categoryName: 'name',
#      categoryResults: 'results',
#      title: 'title',
#      id: 'id'
#      description: 'description'
#    errors:
#      noResults: ''
#    onSelect: (result, response) ->
#      window.location.pathname = result.url
#  )
  $('.sportaide_search input').on 'keyup', (event) =>
    if event.keyCode == 13
      $(".search-box").submit(() ->
        return false;
      )
      window.location.pathname = "/dashboard/lessons/search/#{event.target.value}"

  $('.postcode-search input').on 'keyup', (event) =>
    if event.keyCode == 13
      if $(event.target).val() == ""
        window.location.pathname = "/dashboard/clubs/club_map"
      else
        window.location.pathname = "/dashboard/clubs/club_map/search/#{event.target.value}"

  $('.ui.checkbox').checkbox()

  white = 'rgb(255,255,255)'
  seafoam = 'rgb(30,205,151)'
  #This is the update handler that lets us tween attributes

  onUpdateHandler = ->
    $buttonShapes.attr 'width', buttonProps.buttonWidth
    $buttonShapes.attr 'x', buttonProps.buttonX
    $buttonShapes.attr 'y', buttonProps.buttonY
    $buttonText.attr 'transform', 'scale(' + buttonProps.textScale + ')'
    $buttonText.attr 'x', buttonProps.textX
    $buttonText.attr 'y', buttonProps.textY
    return

  bind_mouseenter = ->
    $('.colins-submit').on 'mouseenter', (e) ->
      hover_tl.restart()
      $('.colins-submit').off 'mouseenter'
      bind_mouseleave()
      return
    return

  bind_mouseleave = ->
    $('.colins-submit').on 'mouseleave', (e) ->
      hover_tl.reverse()
      $('.colins-submit').off 'mouseleave'
      bind_mouseenter()
      return
    return

  $buttonShapes = $('rect.btn-shape')
  $buttonColorShape = $('rect.btn-shape.btn-color')
  $buttonText = $('text.textNode')
  $buttonCheck = $('text.checkNode')
  #These are the button attributes which we will be tweening
  #This will be used with GSAP and the function below to tween
  buttonProps =
    buttonWidth: $buttonShapes.attr('width')
    buttonX: $buttonShapes.attr('x')
    buttonY: $buttonShapes.attr('y')
    textScale: 1
    textX: $buttonText.attr('x')
    textY: $buttonText.attr('y')
  #Finally, create the timelines
  hover_tl = new TimelineMax(tweens: [
    TweenMax.to($buttonText, .15, fill: white)
    TweenMax.to($buttonShapes, .25, fill: seafoam)
  ])
  hover_tl.stop()
  tl = new TimelineMax(onComplete: bind_mouseenter)
  #This is the initial transition, from [submit] to the circle
  tl.append new TimelineMax(
    align: 'start'
    tweens: [
      TweenMax.to($buttonText, .15, fillOpacity: 0)
      TweenMax.to(buttonProps, .25,
        buttonX: (190 - 64) / 2
        buttonWidth: 45
        onUpdate: onUpdateHandler)
      TweenMax.to($buttonShapes, .25, fill: white)
    ]
    onComplete: ->
      $buttonColorShape.css
        'strokeDasharray': 202
        'strokeDashoffset': 202
      return
  )
  #The loading dasharray offset animation…
  tl.append TweenMax.to($buttonColorShape, 1.2,
    strokeDashoffset: 0
    ease: Quad.easeIn
    onComplete: ->
      #Reset these values to their defaults.
      $('.email-subscribe input').val("")
      $buttonColorShape.css
        'strokeDasharray': 460
        'strokeDashoffset': 0
      return
  )
  #The Finish - transition to check
  tl.append new TimelineMax(
    align: 'start'
    tweens: [
      TweenMax.to($buttonShapes, .3, fill: seafoam)
      TweenMax.to($buttonCheck, .15, fillOpacity: 1)
      TweenMax.to(buttonProps, .25,
        buttonX: 3
        buttonWidth: 190
        onUpdate: onUpdateHandler)
    ])
  #The Reset - back to the beginning
  #For demo only - probably you would want to remove this.
  tl.append TweenMax.to($buttonCheck, .1,
    delay: 1
    fillOpacity: 0)
  tl.append new TimelineMax(
    align: 'start'
    tweens: [
      TweenMax.to($buttonShapes, .3, fill: white)
      TweenMax.to($buttonText, .3,
        fill: seafoam
        fillOpacity: 1)
    ]
    onComplete: ->
      $('.colins-submit').removeClass 'is-active'
      return
  )
  tl.stop()
  #-- On Click, we launch into the cool transition

  $(".subscribe-form").submit(() ->
    $('.colins-submit').addClass 'is-active'
    tl.restart()
    $('.colins-submit').off 'mouseenter'
    $('.colins-submit').off 'mouseleave'
    return false
  )
    #-- Add this class to indicate state
  bind_mouseenter()

  $('.email-subscribe input').on 'keyup', (event) ->
    if event.keyCode == 13
      $(".subscribe-form").submit(()->
        $('.colins-submit').addClass 'is-active'
        tl.restart()
        $('.colins-submit').off 'mouseenter'
        $('.colins-submit').off 'mouseleave'
        return false
      )
  # ---
  # generated by js2coffee 2.2.0
  if document.getElementsByClassName('filtr-container').length != 0
    $('.filtr-container').filterizr(
      delay: 10
      delayMode: 'alternate'
      filterInCss:
        opacity: 1
        transform: 'scale(0.95)'
    )


  $('.news-article').on 'click', () ->
    window.location.href = $(this).find('.news-link').attr("href")

  $("#Glide").glide(
    type: "carousel"
  )